import fs from "fs";
import path from "path";
// @ts-ignore
import alasql from "alasql/dist/alasql.js";

// Initialize alasql database
alasql("CREATE DATABASE IF NOT EXISTS sqlock_csv");
alasql("USE sqlock_csv");

const DATA_DIR = process.cwd();
const EMPLOYEE_FILE = path.join(DATA_DIR, "Employee_info.csv");
const LOGS_FILE = path.join(DATA_DIR, "Logs.csv");

let isInitialized = false;

async function initialize() {
  if (isInitialized) return;

  // Load Employee_info
  try {
    if (fs.existsSync(EMPLOYEE_FILE)) {
      await alasql.promise(
        `CREATE TABLE IF NOT EXISTS employee_info; 
         SELECT * INTO employee_info FROM CSV(?, {headers:true})`,
        [EMPLOYEE_FILE]
      );
      console.log("Loaded Employee_info.csv into alasql");
    } else {
      console.error("Employee_info.csv not found at", EMPLOYEE_FILE);
    }
  } catch (e) {
    console.error("Error loading Employee_info.csv", e);
  }

  // Load Logs
  try {
    await alasql.promise("CREATE TABLE IF NOT EXISTS Logs (id INT AUTO_INCREMENT, ts_utc DATETIME, decision STRING, suspicion_score NUMBER, query_template STRING)");

    if (fs.existsSync(LOGS_FILE)) {
      // Check if file is not empty
      const stats = fs.statSync(LOGS_FILE);
      if (stats.size > 0) {
        await alasql.promise(
          `SELECT * INTO Logs FROM CSV(?, {headers:true, separator:','})`,
          [LOGS_FILE]
        );
        console.log("Loaded Logs.csv into alasql");
      }
    }
  } catch (e) {
    console.error("Error loading Logs.csv", e);
  }

  isInitialized = true;
}

export async function executeCsvQuery(sql: string, params: unknown[] = []): Promise<any> {
  if (!isInitialized) {
    await initialize();
  }

  // Alasql uses ? for parameters, same as mysql2
  // However, we need to ensure params are in the right format
  // Dates might need special handling if passed as objects, but alasql usually handles them.

  try {
    // Handle INSERT INTO Logs specially to persist data
    const isInsertLogs = sql.trim().toUpperCase().startsWith("INSERT INTO LOGS");

    // Alasql might not support AUTO_INCREMENT perfectly in CREATE TABLE syntax for in-memory, 
    // but we can manage IDs if needed. For now let's see if it works.
    // Actually, for the Logs table, we might need to generate IDs if they are not provided.
    // The schema in security-events.ts implies ID is generated by DB.
    // In CSV mode, we might need to find the max ID and increment.

    if (isInsertLogs) {
      // If the query expects auto-increment ID, alasql might not do it automatically unless defined.
      // Let's just run the query. If it fails due to missing ID, we might need to adjust.
      // But the query in security-events.ts is:
      // INSERT INTO Logs (decision, suspicion_score, query_template) VALUES (?, ?, ?)
      // It relies on DB to generate ID and ts_utc (maybe? ts_utc is in SELECT but not INSERT?)
      // Wait, security-events.ts INSERT:
      // INSERT INTO Logs (decision, suspicion_score, query_template) VALUES (?, ?, ?)
      // It does NOT insert ts_utc. So the DB must have a default CURRENT_TIMESTAMP.
      // And ID is auto-increment.

      // We need to handle this in Alasql.
      // We can modify the SQL to include id and ts_utc.

      const maxIdResult = await alasql.promise("SELECT MAX(id) as maxId FROM Logs");
      const nextId = (maxIdResult[0]?.maxId || 0) + 1;
      const now = new Date().toISOString().slice(0, 19).replace('T', ' '); // YYYY-MM-DD HH:mm:ss

      // We need to inject these values.
      // This is getting tricky to parse the SQL string reliably.
      // Instead, let's just manually insert for this specific case if we detect it.

      // But to be generic, let's try to use alasql triggers or defaults? Alasql support is limited.
      // Let's just intercept the specific INSERT query from security-events.ts
      if (sql.includes("INSERT INTO Logs")) {
        await alasql.promise(
          "INSERT INTO Logs (id, ts_utc, decision, suspicion_score, query_template) VALUES (?, ?, ?, ?, ?)",
          [nextId, now, ...params]
        );
      } else {
        await alasql.promise(sql, params);
      }

      // Persist to CSV
      await alasql.promise(`SELECT * INTO CSV(?, {headers:true, separator:','}) FROM Logs`, [LOGS_FILE]);
      return []; // INSERT returns nothing usually
    }

    const result = await alasql.promise(sql, params);
    return result;
  } catch (error) {
    console.error("Alasql query error:", error);
    throw error;
  }
}
